optimizer:
  learning_rate:
    - [100000, 5.0e-5]
validation_steps:
  2500

checkpoint_steps:
  5000

dataset:
  movingcables

sintel:
  0

kitti:
  0

hd1k:
  0

target_shape:
  [384, 640]

kitti_15:
  True
